// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wordcount

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordCountClient is the client API for WordCount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordCountClient interface {
	CountWords(ctx context.Context, in *Text, opts ...grpc.CallOption) (*CountedWords, error)
}

type wordCountClient struct {
	cc grpc.ClientConnInterface
}

func NewWordCountClient(cc grpc.ClientConnInterface) WordCountClient {
	return &wordCountClient{cc}
}

func (c *wordCountClient) CountWords(ctx context.Context, in *Text, opts ...grpc.CallOption) (*CountedWords, error) {
	out := new(CountedWords)
	err := c.cc.Invoke(ctx, "/WordCount/CountWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordCountServer is the server API for WordCount service.
// All implementations must embed UnimplementedWordCountServer
// for forward compatibility
type WordCountServer interface {
	CountWords(context.Context, *Text) (*CountedWords, error)
	mustEmbedUnimplementedWordCountServer()
}

// UnimplementedWordCountServer must be embedded to have forward compatible implementations.
type UnimplementedWordCountServer struct {
}

func (UnimplementedWordCountServer) CountWords(context.Context, *Text) (*CountedWords, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountWords not implemented")
}
func (UnimplementedWordCountServer) mustEmbedUnimplementedWordCountServer() {}

// UnsafeWordCountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordCountServer will
// result in compilation errors.
type UnsafeWordCountServer interface {
	mustEmbedUnimplementedWordCountServer()
}

func RegisterWordCountServer(s grpc.ServiceRegistrar, srv WordCountServer) {
	s.RegisterService(&WordCount_ServiceDesc, srv)
}

func _WordCount_CountWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordCountServer).CountWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WordCount/CountWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordCountServer).CountWords(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

// WordCount_ServiceDesc is the grpc.ServiceDesc for WordCount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordCount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WordCount",
	HandlerType: (*WordCountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountWords",
			Handler:    _WordCount_CountWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/word_count.proto",
}
