// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package getrandomnumbers

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetRandomNumbersClient is the client API for GetRandomNumbers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRandomNumbersClient interface {
	GetNumbers(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*NumbersList, error)
}

type getRandomNumbersClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRandomNumbersClient(cc grpc.ClientConnInterface) GetRandomNumbersClient {
	return &getRandomNumbersClient{cc}
}

func (c *getRandomNumbersClient) GetNumbers(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*NumbersList, error) {
	out := new(NumbersList)
	err := c.cc.Invoke(ctx, "/GetRandomNumbers/GetNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRandomNumbersServer is the server API for GetRandomNumbers service.
// All implementations must embed UnimplementedGetRandomNumbersServer
// for forward compatibility
type GetRandomNumbersServer interface {
	GetNumbers(context.Context, *Amount) (*NumbersList, error)
	mustEmbedUnimplementedGetRandomNumbersServer()
}

// UnimplementedGetRandomNumbersServer must be embedded to have forward compatible implementations.
type UnimplementedGetRandomNumbersServer struct {
}

func (UnimplementedGetRandomNumbersServer) GetNumbers(context.Context, *Amount) (*NumbersList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumbers not implemented")
}
func (UnimplementedGetRandomNumbersServer) mustEmbedUnimplementedGetRandomNumbersServer() {}

// UnsafeGetRandomNumbersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRandomNumbersServer will
// result in compilation errors.
type UnsafeGetRandomNumbersServer interface {
	mustEmbedUnimplementedGetRandomNumbersServer()
}

func RegisterGetRandomNumbersServer(s grpc.ServiceRegistrar, srv GetRandomNumbersServer) {
	s.RegisterService(&GetRandomNumbers_ServiceDesc, srv)
}

func _GetRandomNumbers_GetNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRandomNumbersServer).GetNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GetRandomNumbers/GetNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRandomNumbersServer).GetNumbers(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRandomNumbers_ServiceDesc is the grpc.ServiceDesc for GetRandomNumbers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRandomNumbers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetRandomNumbers",
	HandlerType: (*GetRandomNumbersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumbers",
			Handler:    _GetRandomNumbers_GetNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/getrandomnumbers.proto",
}
