// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: grpc/proto/word_count.proto

package wordcount

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_word_count_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_word_count_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_grpc_proto_word_count_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CountedWords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*CountedWords_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *CountedWords) Reset() {
	*x = CountedWords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_word_count_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountedWords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountedWords) ProtoMessage() {}

func (x *CountedWords) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_word_count_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountedWords.ProtoReflect.Descriptor instead.
func (*CountedWords) Descriptor() ([]byte, []int) {
	return file_grpc_proto_word_count_proto_rawDescGZIP(), []int{1}
}

func (x *CountedWords) GetEntries() []*CountedWords_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CountedWords_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word  string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountedWords_Entry) Reset() {
	*x = CountedWords_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_word_count_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountedWords_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountedWords_Entry) ProtoMessage() {}

func (x *CountedWords_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_word_count_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountedWords_Entry.ProtoReflect.Descriptor instead.
func (*CountedWords_Entry) Descriptor() ([]byte, []int) {
	return file_grpc_proto_word_count_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CountedWords_Entry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *CountedWords_Entry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_grpc_proto_word_count_proto protoreflect.FileDescriptor

var file_grpc_proto_word_count_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72,
	0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x0c, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x31, 0x0a, 0x09, 0x57,
	0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x05, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x0d, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6d,
	0x65, 0x69, 0x64, 0x61, 0x2d, 0x72, 0x61, 0x70, 0x68, 0x61, 0x65, 0x6c, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_word_count_proto_rawDescOnce sync.Once
	file_grpc_proto_word_count_proto_rawDescData = file_grpc_proto_word_count_proto_rawDesc
)

func file_grpc_proto_word_count_proto_rawDescGZIP() []byte {
	file_grpc_proto_word_count_proto_rawDescOnce.Do(func() {
		file_grpc_proto_word_count_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_word_count_proto_rawDescData)
	})
	return file_grpc_proto_word_count_proto_rawDescData
}

var file_grpc_proto_word_count_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_word_count_proto_goTypes = []interface{}{
	(*Text)(nil),               // 0: Text
	(*CountedWords)(nil),       // 1: CountedWords
	(*CountedWords_Entry)(nil), // 2: CountedWords.Entry
}
var file_grpc_proto_word_count_proto_depIdxs = []int32{
	2, // 0: CountedWords.entries:type_name -> CountedWords.Entry
	0, // 1: WordCount.CountWords:input_type -> Text
	1, // 2: WordCount.CountWords:output_type -> CountedWords
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_word_count_proto_init() }
func file_grpc_proto_word_count_proto_init() {
	if File_grpc_proto_word_count_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_word_count_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_word_count_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountedWords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_word_count_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountedWords_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_word_count_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_word_count_proto_goTypes,
		DependencyIndexes: file_grpc_proto_word_count_proto_depIdxs,
		MessageInfos:      file_grpc_proto_word_count_proto_msgTypes,
	}.Build()
	File_grpc_proto_word_count_proto = out.File
	file_grpc_proto_word_count_proto_rawDesc = nil
	file_grpc_proto_word_count_proto_goTypes = nil
	file_grpc_proto_word_count_proto_depIdxs = nil
}
