// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package typeuint64

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TypeAllClient is the client API for TypeAll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypeAllClient interface {
	TypeAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResult, error)
}

type typeAllClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeAllClient(cc grpc.ClientConnInterface) TypeAllClient {
	return &typeAllClient{cc}
}

func (c *typeAllClient) TypeAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResult, error) {
	out := new(EmptyResult)
	err := c.cc.Invoke(ctx, "/TypeAll/TypeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeAllServer is the server API for TypeAll service.
// All implementations must embed UnimplementedTypeAllServer
// for forward compatibility
type TypeAllServer interface {
	TypeAll(context.Context, *Request) (*EmptyResult, error)
	mustEmbedUnimplementedTypeAllServer()
}

// UnimplementedTypeAllServer must be embedded to have forward compatible implementations.
type UnimplementedTypeAllServer struct {
}

func (UnimplementedTypeAllServer) TypeAll(context.Context, *Request) (*EmptyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TypeAll not implemented")
}
func (UnimplementedTypeAllServer) mustEmbedUnimplementedTypeAllServer() {}

// UnsafeTypeAllServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeAllServer will
// result in compilation errors.
type UnsafeTypeAllServer interface {
	mustEmbedUnimplementedTypeAllServer()
}

func RegisterTypeAllServer(s grpc.ServiceRegistrar, srv TypeAllServer) {
	s.RegisterService(&TypeAll_ServiceDesc, srv)
}

func _TypeAll_TypeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeAllServer).TypeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TypeAll/TypeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeAllServer).TypeAll(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TypeAll_ServiceDesc is the grpc.ServiceDesc for TypeAll service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypeAll_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TypeAll",
	HandlerType: (*TypeAllServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TypeAll",
			Handler:    _TypeAll_TypeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/grpc/proto/typeuint64.proto",
}
