// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: grpc/proto/doubletype.proto

package doubletype

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []int32 `protobuf:"varint,1,rep,packed,name=entries,proto3" json:"entries,omitempty"`
}

func (x *NumberList) Reset() {
	*x = NumberList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_doubletype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberList) ProtoMessage() {}

func (x *NumberList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_doubletype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberList.ProtoReflect.Descriptor instead.
func (*NumberList) Descriptor() ([]byte, []int) {
	return file_grpc_proto_doubletype_proto_rawDescGZIP(), []int{0}
}

func (x *NumberList) GetEntries() []int32 {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_doubletype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_doubletype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_grpc_proto_doubletype_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_grpc_proto_doubletype_proto protoreflect.FileDescriptor

var file_grpc_proto_doubletype_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a,
	0x0a, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x2f, 0x0a, 0x0a, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x0b,
	0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6d, 0x65, 0x69, 0x64, 0x61, 0x2d, 0x72, 0x61, 0x70,
	0x68, 0x61, 0x65, 0x6c, 0x2f, 0x61, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_doubletype_proto_rawDescOnce sync.Once
	file_grpc_proto_doubletype_proto_rawDescData = file_grpc_proto_doubletype_proto_rawDesc
)

func file_grpc_proto_doubletype_proto_rawDescGZIP() []byte {
	file_grpc_proto_doubletype_proto_rawDescOnce.Do(func() {
		file_grpc_proto_doubletype_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_doubletype_proto_rawDescData)
	})
	return file_grpc_proto_doubletype_proto_rawDescData
}

var file_grpc_proto_doubletype_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_doubletype_proto_goTypes = []interface{}{
	(*NumberList)(nil), // 0: NumberList
	(*Result)(nil),     // 1: Result
}
var file_grpc_proto_doubletype_proto_depIdxs = []int32{
	0, // 0: DoubleType.Average:input_type -> NumberList
	1, // 1: DoubleType.Average:output_type -> Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_doubletype_proto_init() }
func file_grpc_proto_doubletype_proto_init() {
	if File_grpc_proto_doubletype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_doubletype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_doubletype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_doubletype_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_doubletype_proto_goTypes,
		DependencyIndexes: file_grpc_proto_doubletype_proto_depIdxs,
		MessageInfos:      file_grpc_proto_doubletype_proto_msgTypes,
	}.Build()
	File_grpc_proto_doubletype_proto = out.File
	file_grpc_proto_doubletype_proto_rawDesc = nil
	file_grpc_proto_doubletype_proto_goTypes = nil
	file_grpc_proto_doubletype_proto_depIdxs = nil
}
